In [5]:
import numpy as np
# Generate a random 2D NumPy array with dimensions 3 x 4 x 5
tensor = np.random.randint(3, size=(3, 4, 5)) # (block, rows, columns)

# Print the generated vector
print("\nRandom tensor:")
print(tensor)


Random tensor:
[[[2 0 1 2 2]
  [0 2 1 0 2]
  [0 1 1 2 0]
  [1 0 0 1 2]]

 [[1 1 0 1 0]
  [2 2 2 2 1]
  [2 2 1 0 2]
  [0 2 2 0 2]]

 [[1 0 0 2 1]
  [0 0 2 2 1]
  [2 1 2 2 1]
  [1 2 0 1 2]]]


In [9]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
if array1 == array2:
    print(equal_result)
elif = array1 != array2:
    print("\nInequality Comparison Result:")


SyntaxError: invalid syntax (2939100188.py, line 5)

In [15]:
words = ['play', 'filling', 'bar', 'theatre', 'easygoing', 'date', 'lead', 'that', 'story',  'island']
uppercase = [words.upper('') for word in words]
print(uppercase)

AttributeError: 'list' object has no attribute 'upper'